"""userReport and user model update

Revision ID: 270511160ea3
Revises: 0bef09b3aafc
Create Date: 2025-05-03 00:02:21.829133

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = '270511160ea3'
down_revision = '0bef09b3aafc'
branch_labels = None
depends_on = None


def upgrade():
    # Get database connection and inspector
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)

    # Check if contribution column exists in user table
    user_columns = [col['name'] for col in inspector.get_columns('user')]
    if 'contribution' not in user_columns:
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.add_column(sa.Column('contribution', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('claim_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('chat_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('admin_notes', sa.String(length=500), nullable=True))
        batch_op.create_foreign_key('fk_user_report_claim', 'verification_claim', ['claim_id'], ['id'])
        batch_op.create_foreign_key('fk_user_report_post', 'post', ['post_id'], ['id'])
        batch_op.create_foreign_key('fk_user_report_chat', 'chat', ['chat_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_report', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_report_chat', type_='foreignkey')
        batch_op.drop_constraint('fk_user_report_post', type_='foreignkey')
        batch_op.drop_constraint('fk_user_report_claim', type_='foreignkey')
        batch_op.drop_column('admin_notes')
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('type')
        batch_op.drop_column('chat_id')
        batch_op.drop_column('claim_id')
        batch_op.drop_column('post_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('contribution')

    # ### end Alembic commands ###
