"""Add contribution field to User model

Revision ID: 7ff8ca535898
Revises: 0bef09b3aafc
Create Date: 2025-04-20 22:35:02.020667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff8ca535898'
down_revision = '0bef09b3aafc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contribution', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('contribution')

    # ### end Alembic commands ###
